import type { Reciter } from "@/types";

export const MS_PER_HOUR = 3600000;
export const MS_PER_MINUTE = 60000;
export const MS_PER_SECOND = 1000;
export const NOTIF_WARNING_MS = 30000;
export const DEFAULT_LAT = 30.0444;
export const DEFAULT_LNG = 31.2357;
export const DEFAULT_LOCATION_NAME = "القاهرة";

export const PRAYER_ARABIC: Record<string, string> = {
  Fajr: 'الفجر',
  Dhuhr: 'الظهر',
  Asr: 'العصر',
  Maghrib: 'المغرب',
  Isha: 'العشاء',
};

export const DEFAULT_SETTINGS = {
  language: "ar" as const,
  theme: "dark" as const,
  prayerMethod: 5, // Egyptian General Authority of Survey
  madhab: 0 as const, // Shafi'i
  reciterId: "ar.alafasy",
  quranFontSize: 28,
  translationLang: "en.asad",
  notificationsEnabled: false,
  eyeComfort: false,
  salawatEnabled: false,
  salawatInterval: 10, // 10 minutes default
  prayerReminderEnabled: false,
  prayerReminderMinutes: 10, // 10 minutes before prayer
  adhanEnabled: true, // play adhan at prayer time
  adhanSound: 'default', // default, algeria, makka, rashed
  pushEnabled: false, // push notifications when app is closed
};

export const RECITERS: Reciter[] = [
  { id: "ar.husarymujawwad", name: "Husary (Mujawwad)", nameAr: "محمود خليل الحصري", style: "مجود" },
  { id: "ar.alafasy", name: "Mishary Alafasy", nameAr: "مشاري العفاسي", style: "مجود" },
  { id: "ar.mahermuaiqly", name: "Maher Al Muaiqly", nameAr: "ماهر المعيقلي", style: "مرتل" },
  { id: "ar.shaatree", name: "Abu Bakr Ash-Shaatree", nameAr: "أبو بكر الشاطري", style: "مرتل" },
  { id: "ar.hudhaify", name: "Ali Al-Hudhaify", nameAr: "علي الحذيفي", style: "مرتل" },
  { id: "ar.minshawi", name: "Mohammad Siddiq Minshawi", nameAr: "محمد صديق المنشاوي", style: "مجود" },
];

export const PRAYER_METHODS = [
  { value: 0, name: "Shia Ithna Ashari", nameAr: "شيعة اثنا عشرية" },
  { value: 1, name: "University of Islamic Sciences, Karachi", nameAr: "جامعة العلوم الإسلامية - كراتشي" },
  { value: 2, name: "Islamic Society of North America", nameAr: "الجمعية الإسلامية لأمريكا الشمالية" },
  { value: 3, name: "Muslim World League", nameAr: "رابطة العالم الإسلامي" },
  { value: 4, name: "Umm al-Qura University, Makkah", nameAr: "جامعة أم القرى - مكة المكرمة" },
  { value: 5, name: "Egyptian General Authority of Survey", nameAr: "الهيئة المصرية العامة للمساحة" },
  { value: 7, name: "Institute of Geophysics, University of Tehran", nameAr: "معهد الجيوفيزياء - جامعة طهران" },
  { value: 8, name: "Gulf Region", nameAr: "منطقة الخليج" },
  { value: 9, name: "Kuwait", nameAr: "الكويت" },
  { value: 10, name: "Qatar", nameAr: "قطر" },
  { value: 11, name: "Majlis Ugama Islam Singapura", nameAr: "مجلس الشؤون الإسلامية - سنغافورة" },
  { value: 12, name: "UOIF (France)", nameAr: "اتحاد المنظمات الإسلامية - فرنسا" },
  { value: 13, name: "Diyanet İşleri Başkanlığı (Turkey)", nameAr: "رئاسة الشؤون الدينية - تركيا" },
  { value: 14, name: "Spiritual Administration of Muslims of Russia", nameAr: "الإدارة الروحية لمسلمي روسيا" },
];

export const MADHAB_OPTIONS = [
  { value: 0 as const, name: "Shafi'i / Maliki / Hanbali", nameAr: "شافعي / مالكي / حنبلي" },
  { value: 1 as const, name: "Hanafi", nameAr: "حنفي" },
];

export const PRAYER_META = [
  { key: "Fajr", nameAr: "الفجر", icon: "🌅", colorVar: "--color-fajr" },
  { key: "Dhuhr", nameAr: "الظهر", icon: "☀️", colorVar: "--color-dhuhr" },
  { key: "Asr", nameAr: "العصر", icon: "🌤️", colorVar: "--color-asr" },
  { key: "Maghrib", nameAr: "المغرب", icon: "🌆", colorVar: "--color-maghrib" },
  { key: "Isha", nameAr: "العشاء", icon: "🌙", colorVar: "--color-isha" },
];

export const TASBIEH_PHRASES = [
  { text: "سبحان الله", meaning: "Glory be to Allah" },
  { text: "الحمد لله", meaning: "All praise is for Allah" },
  { text: "الله أكبر", meaning: "Allah is the Greatest" },
  { text: "لا إله إلا الله", meaning: "There is no god but Allah" },
  { text: "أستغفر الله", meaning: "I seek forgiveness from Allah" },
  { text: "سبحان الله وبحمده", meaning: "Glory be to Allah and all praise" },
  { text: "لا حول ولا قوة إلا بالله", meaning: "There is no power except with Allah" },
  { text: "اللهم صلِّ على محمد", meaning: "O Allah, send blessings upon Muhammad ﷺ" },
];

export const TRANSLATIONS = {
  ar: {
    appName: "زاد مسلم",
    tagline: "زادك في كل يوم",
    greeting: "السلام عليكم ورحمة الله",
    home: "الرئيسية",
    quran: "القرآن",
    prayer: "الصلاة",
    azkar: "الأذكار",
    more: "المزيد",
    settings: "الإعدادات",
    nextPrayer: "الصلاة القادمة",
    remaining: "متبقي",
    continueReading: "تابع القراءة",
    hadithToday: "حديث اليوم",
    surah: "سورة",
    ayah: "آية",
    search: "بحث",
    bookmarks: "المحفوظات",
    reciter: "القارئ",
    morning: "أذكار الصباح",
    evening: "أذكار المساء",
    afterPrayer: "أذكار بعد الصلاة",
    sleep: "أذكار النوم",
    eating: "أذكار الأكل",
    travel: "أذكار السفر",
    tasbeeh: "تسبيح",
    tapToCount: "اضغط للتسبيح",
    rounds: "دورات",
    target: "الهدف",
    method: "طريقة الحساب",
    madhab: "المذهب",
    fontSize: "حجم الخط",
    language: "اللغة",
    theme: "المظهر",
    dark: "داكن",
    light: "فاتح",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "إعادة المحاولة",
    noResults: "لا توجد نتائج",
    save: "حفظ",
    cancel: "إلغاء",
    done: "تم",
    quranSearch: "ابحث في القرآن الكريم...",
    selectCity: "اختر المدينة",
    locationDenied: "تم رفض الوصول إلى الموقع",
    useManualLocation: "استخدم البحث اليدوي",
    mushaf: "المصحف",
    surahMode: "عرض السور",
    mushafMode: "عرض المصحف",
    page: "صفحة",
    juz: "جزء",
    hizb: "حزب",
    selectReciter: "اختر القارئ",
    reciterStyle: "نمط القراءة",
    mujawwad: "مجود",
    murattal: "مرتل",
    hadith: "الحديث",
    narrator: "الراوي",
    source: "المصدر",
    grade: "الدرجة",
    salawat: "الصلاة على النبي ﷺ",
    salawatCount: "عدد الصلوات",
    dailyTarget: "الهدف اليومي",
    reset: "إعادة",
    namesOfAllah: "أسماء الله الحسنى",
    allPages: "صفحة",
    of: "من",
    goToPage: "انتقل إلى صفحة",
    bookmark: "حفظ",
    bookmarked: "تم الحفظ",
    lastRead: "آخر قراءة",
    salawatReminder: "تذكير الصلاة على النبي",
    salawatInterval: "الفترة (بالدقائق)",
    salawat5min: "كل 5 دقائق",
    salawat10min: "كل 10 دقائق",
    salawat15min: "كل 15 دقيقة",
    salawat30min: "كل 30 دقيقة",
    salawatNotifTitle: "اللهم صلِّ على محمد ﷺ",
    salawatNotifBody: "لا تنسَ الصلاة على النبي ﷺ",
    prayerReminder: "تذكير الصلاة",
    prayerReminderMinutes: "وقت التذكير",
    prayerReminderBody: "اقترب وقت صلاة {prayer}",
    adhan: "أذان الصلاة",
    adhanSound: "صوت الأذان",
    adhanEnabled: "تشغيل الأذان",
    adhanDisabled: "إيقاف الأذان",
    adhanNotifTitle: "حان وقت الصلاة",
    adhanNotifBody: "حان وقت صلاة {prayer} - أذان الله أكبر",
    adhanToastTitle: "الله أكبر",
    pushNotifications: "إشعارات فورية",
    pushEnabled: "تفعيل الإشعارات",
    pushDisabled: "إيقاف الإشعارات",
    pushNotSupported: "غير مدعوم في هذا المتصفح",
    pushSubscribed: "مفعّل — الإشعارات هتوصلك حتى لو التطبيق مقفول",
    pushUnsubscribed: "تم إيقاف الإشعارات",
    pushTestTitle: "إشعار تجريبي",
    pushTestBody: "هذا إشعار تجريبي من زاد مسلم ✅",
    pushBlocked: "الإشعارات محظورة — فعّلها من إعدادات المتصفح",
    pushDescription: "الإشعارات الفورية بتوصلك حتى لو التطبيق مقفول — الأذان، تذكير الصلاة، والصلاة على النبي ﷺ",
  },
  en: {
    appName: "Zad Muslim",
    tagline: "Your provision every day",
    greeting: "Peace be upon you",
    home: "Home",
    quran: "Quran",
    prayer: "Prayer",
    azkar: "Azkar",
    more: "More",
    settings: "Settings",
    nextPrayer: "Next Prayer",
    remaining: "remaining",
    continueReading: "Continue Reading",
    hadithToday: "Hadith of the Day",
    surah: "Surah",
    ayah: "Ayah",
    search: "Search",
    bookmarks: "Bookmarks",
    reciter: "Reciter",
    morning: "Morning Adhkar",
    evening: "Evening Adhkar",
    afterPrayer: "After Prayer Adhkar",
    sleep: "Sleep Adhkar",
    eating: "Eating Adhkar",
    travel: "Travel Adhkar",
    tasbeeh: "Tasbeeh",
    tapToCount: "Tap to Count",
    rounds: "Rounds",
    target: "Target",
    method: "Calculation Method",
    madhab: "Madhab",
    fontSize: "Font Size",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    loading: "Loading...",
    error: "An error occurred",
    retry: "Retry",
    noResults: "No results found",
    save: "Save",
    cancel: "Cancel",
    done: "Done",
    quranSearch: "Search the Holy Quran...",
    selectCity: "Select City",
    locationDenied: "Location access denied",
    useManualLocation: "Use manual search",
    mushaf: "Mus'haf",
    surahMode: "Surah View",
    mushafMode: "Mus'haf View",
    page: "Page",
    juz: "Juz",
    hizb: "Hizb",
    selectReciter: "Select Reciter",
    reciterStyle: "Recitation Style",
    mujawwad: "Mujawwad",
    murattal: "Murattal",
    hadith: "Hadith",
    narrator: "Narrator",
    source: "Source",
    grade: "Grade",
    salawat: "Salawat on Prophet ﷺ",
    salawatCount: "Salawat Count",
    dailyTarget: "Daily Target",
    reset: "Reset",
    namesOfAllah: "Names of Allah",
    allPages: "Page",
    of: "of",
    goToPage: "Go to page",
    bookmark: "Bookmark",
    bookmarked: "Bookmarked",
    lastRead: "Last Read",
    salawatReminder: "Salawat Reminder",
    salawatInterval: "Interval (minutes)",
    salawat5min: "Every 5 minutes",
    salawat10min: "Every 10 minutes",
    salawat15min: "Every 15 minutes",
    salawat30min: "Every 30 minutes",
    salawatNotifTitle: "O Allah, send blessings upon Muhammad ﷺ",
    salawatNotifBody: "Don't forget to send Salawat on the Prophet ﷺ",
    prayerReminder: "Prayer Reminder",
    prayerReminderMinutes: "Reminder Time",
    prayerReminderBody: "Time for {prayer} prayer is approaching",
    adhan: "Prayer Adhan",
    adhanSound: "Adhan Sound",
    adhanEnabled: "Enable Adhan",
    adhanDisabled: "Disable Adhan",
    adhanNotifTitle: "Prayer Time",
    adhanNotifBody: "It's time for {prayer} prayer - Allahu Akbar",
    adhanToastTitle: "Allahu Akbar",
    pushNotifications: "Push Notifications",
    pushEnabled: "Enable Notifications",
    pushDisabled: "Disable Notifications",
    pushNotSupported: "Not supported in this browser",
    pushSubscribed: "Active — notifications will reach you even when app is closed",
    pushUnsubscribed: "Notifications disabled",
    pushTestTitle: "Test Notification",
    pushTestBody: "This is a test notification from Zad Muslim ✅",
    pushBlocked: "Notifications blocked — enable in browser settings",
    pushDescription: "Push notifications reach you even when app is closed — Adhan, prayer reminders, and Salawat ﷺ",
  },
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.ar;

export const PRAYER_REMINDER_INTERVALS = [
  { value: 5, nameAr: "قبل الصلاة بـ 5 دقائق", nameEn: "5 min before" },
  { value: 10, nameAr: "قبل الصلاة بـ 10 دقائق", nameEn: "10 min before" },
  { value: 15, nameAr: "قبل الصلاة بـ 15 دقيقة", nameEn: "15 min before" },
  { value: 20, nameAr: "قبل الصلاة بـ 20 دقيقة", nameEn: "20 min before" },
  { value: 30, nameAr: "قبل الصلاة بـ 30 دقيقة", nameEn: "30 min before" },
];

export const SALAWAT_INTERVALS = [
  { value: 1, nameAr: "كل دقيقة", nameEn: "Every 1 min" },
  { value: 5, nameAr: "كل 5 دقائق", nameEn: "Every 5 min" },
  { value: 10, nameAr: "كل 10 دقائق", nameEn: "Every 10 min" },
  { value: 15, nameAr: "كل 15 دقيقة", nameEn: "Every 15 min" },
  { value: 30, nameAr: "كل 30 دقيقة", nameEn: "Every 30 min" },
];

export const ADHAN_SOUNDS = [
  { value: 'default', nameAr: 'افتراضي (نغمات)', nameEn: 'Default (Tones)' },
  { value: 'algeria', nameAr: 'الجزائر', nameEn: 'Algeria' },
  { value: 'makka', nameAr: 'مكة المكرمة', nameEn: 'Makkah' },
  { value: 'rashed', nameAr: 'الشيخ راشد العفاسي', nameEn: 'Rashed Al-Afasy' },
];
